version: "3"

services:
  minio:
    image: minio/minio:latest
    container_name: ${CONTAINER_NAME:-minio}
    restart: always
    networks:
      - minio
    ports:
      - ${API_PORT:-9000}:9000
      - ${CONSOLE_PORT:-9001}:9001
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


networks:
  minio:


volumes:
  minio_storage:
