version: "3"

services:
  influxdb:
    image: influxdb:latest
    container_name: ${CONTAINER_NAME:-influxdb}
    networks:
      - database
    restart: always
    ports:
      - ${INFLUXDB_PORT:-8086}:8086
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}


networks:
  database:


volumes:
  influxdb_data:
  influxdb_config:
